// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CampaignsPostRequestBody_provider_routing_rules_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "send")]
        #pragma warning disable CS1591
        Send,
        #pragma warning restore CS1591
        [EnumMember(Value = "do_not_send")]
        #pragma warning disable CS1591
        Do_not_send,
        #pragma warning restore CS1591
    }
}
