// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.Add
{
    /// <summary>Enrichment type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddPostRequestBody_type
    {
        [EnumMember(Value = "work_email_enrichment")]
        #pragma warning disable CS1591
        Work_email_enrichment,
        #pragma warning restore CS1591
        [EnumMember(Value = "fully_enriched_profile")]
        #pragma warning disable CS1591
        Fully_enriched_profile,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_verification")]
        #pragma warning disable CS1591
        Email_verification,
        #pragma warning restore CS1591
        [EnumMember(Value = "joblisting")]
        #pragma warning disable CS1591
        Joblisting,
        #pragma warning restore CS1591
        [EnumMember(Value = "technologies")]
        #pragma warning disable CS1591
        Technologies,
        #pragma warning restore CS1591
        [EnumMember(Value = "news")]
        #pragma warning disable CS1591
        News,
        #pragma warning restore CS1591
        [EnumMember(Value = "funding")]
        #pragma warning disable CS1591
        Funding,
        #pragma warning restore CS1591
    }
}
