// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ai-agents\{id}\activity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Instantly.OpenApiClient.api.v2.aiAgents.item.activity.item collection</summary>
        /// <param name="position">Activity ID</param>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity.Item.WithActivityItemRequestBuilder"/></returns>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity.Item.WithActivityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("activityId", position);
                return new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity.Item.WithActivityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity.ActivityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/{id}/activity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Item.Activity.ActivityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/{id}/activity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
