// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.FilterOptions;
using Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Item;
using Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Recipes;
using Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Sources;
using Soenneker.Instantly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\supersearch-enrichment\company-lists
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompanyListsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filterOptions property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.FilterOptions.FilterOptionsRequestBuilder FilterOptions
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.FilterOptions.FilterOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recipes property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Recipes.RecipesRequestBuilder Recipes
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Recipes.RecipesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sources property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Sources.SourcesRequestBuilder Sources
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Sources.SourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Instantly.OpenApiClient.api.v2.supersearchEnrichment.companyLists.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Item.WithCompanyListItemRequestBuilder"/></returns>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Item.WithCompanyListItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("companyListId", position);
                return new global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.Item.WithCompanyListItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompanyListsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/supersearch-enrichment/company-lists{?cursor*,limit*,search*,starting_after*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompanyListsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/supersearch-enrichment/company-lists{?cursor*,limit*,search*,starting_after*}", rawUrl)
        {
        }
        /// <summary>
        /// Requires one of the following scopes: `supersearch_enrichments:read`, `supersearch_enrichments:all`, `all:read`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder.CompanyListsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder.CompanyListsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists402Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists200Response>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.ListCompanyLists200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Requires one of the following scopes: `supersearch_enrichments:create`, `supersearch_enrichments:all`, `all:create`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList202Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList202Response?> PostAsync(global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyListRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList202Response> PostAsync(global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyListRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList402Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList202Response>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyList202Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Requires one of the following scopes: `supersearch_enrichments:read`, `supersearch_enrichments:all`, `all:read`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder.CompanyListsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder.CompanyListsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Requires one of the following scopes: `supersearch_enrichments:create`, `supersearch_enrichments:all`, `all:create`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyListRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Instantly.OpenApiClient.Models.CreateCompanyListRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.CompanyLists.CompanyListsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Requires one of the following scopes: `supersearch_enrichments:read`, `supersearch_enrichments:all`, `all:read`, `all:all`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompanyListsRequestBuilderGetQueryParameters 
        {
            /// <summary>Deprecated alias of `starting_after`. Pass the `next_cursor` value from the previous response. Ignored when `starting_after` is also sent.</summary>
            [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>The number of items to return</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("search")]
            public string? Search { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("search")]
            public string Search { get; set; }
            #pragma warning restore CS1591
#endif
            /// <summary>Pagination cursor. Pass the `next_starting_after` value from the previous response. Takes precedence over the deprecated `cursor` when both are sent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("starting_after")]
            public string? StartingAfter { get; set; }
#nullable restore
#else
            [QueryParameter("starting_after")]
            public string StartingAfter { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
