// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus
{
    /// <summary>
    /// Summary of sending account availability. May be missing when campaign is out of schedule.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SendingStatusGetResponse_diagnostics_accounts_summary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of accounts available to send</summary>
        public double? Available { get; set; }
        /// <summary>Total number of connected sending accounts</summary>
        public double? TotalConnected { get; set; }
        /// <summary>Breakdown of unavailable accounts by reason</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary_unavailable? Unavailable { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary_unavailable Unavailable { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary"/> and sets the default values.
        /// </summary>
        public SendingStatusGetResponse_diagnostics_accounts_summary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available", n => { Available = n.GetDoubleValue(); } },
                { "total_connected", n => { TotalConnected = n.GetDoubleValue(); } },
                { "unavailable", n => { Unavailable = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary_unavailable>(global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary_unavailable.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("available", Available);
            writer.WriteDoubleValue("total_connected", TotalConnected);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.Campaigns.Item.SendingStatus.SendingStatusGetResponse_diagnostics_accounts_summary_unavailable>("unavailable", Unavailable);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
