// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.BackgroundJobs
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetEntity_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign")]
        #pragma warning disable CS1591
        Campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspace")]
        #pragma warning disable CS1591
        Workspace,
        #pragma warning restore CS1591
    }
}
