// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemBranch2"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiAgentPayloadAnyOf4TagsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemBranch2? AiAgentPayloadAnyOf4TagsItemBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemBranch2 AiAgentPayloadAnyOf4TagsItemBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemWrapper? AiAgentPayloadAnyOf4TagsItemWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemWrapper AiAgentPayloadAnyOf4TagsItemWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItem();
            if("AiAgentPayloadAnyOf4TagsItemBranch2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AiAgentPayloadAnyOf4TagsItemBranch2 = new global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemBranch2();
            }
            else if("AiAgentPayloadAnyOf4TagsItemWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AiAgentPayloadAnyOf4TagsItemWrapper = new global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemWrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AiAgentPayloadAnyOf4TagsItemBranch2 != null)
            {
                return AiAgentPayloadAnyOf4TagsItemBranch2.GetFieldDeserializers();
            }
            else if(AiAgentPayloadAnyOf4TagsItemWrapper != null)
            {
                return AiAgentPayloadAnyOf4TagsItemWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AiAgentPayloadAnyOf4TagsItemBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemBranch2>(null, AiAgentPayloadAnyOf4TagsItemBranch2);
            }
            else if(AiAgentPayloadAnyOf4TagsItemWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf4TagsItemWrapper>(null, AiAgentPayloadAnyOf4TagsItemWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
