// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The benefits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Benefits { get; set; }
#nullable restore
#else
        public List<string> Benefits { get; set; }
#endif
        /// <summary>The company_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CompanySize { get; set; }
#nullable restore
#else
        public List<string> CompanySize { get; set; }
#endif
        /// <summary>The customer_goals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomerGoals { get; set; }
#nullable restore
#else
        public List<string> CustomerGoals { get; set; }
#endif
        /// <summary>The industry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Industry { get; set; }
#nullable restore
#else
        public List<string> Industry { get; set; }
#endif
        /// <summary>The job_title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemJobTitle? JobTitle { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemJobTitle JobTitle { get; set; }
#endif
        /// <summary>The keywords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemKeywords? Keywords { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemKeywords Keywords { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The problems_solved property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ProblemsSolved { get; set; }
#nullable restore
#else
        public List<string> ProblemsSolved { get; set; }
#endif
        /// <summary>The success_stories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuccessStories { get; set; }
#nullable restore
#else
        public string SuccessStories { get; set; }
#endif
        /// <summary>The usp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Usp { get; set; }
#nullable restore
#else
        public string Usp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItem"/> and sets the default values.
        /// </summary>
        public AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "benefits", n => { Benefits = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "company_size", n => { CompanySize = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "customer_goals", n => { CustomerGoals = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "industry", n => { Industry = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "job_title", n => { JobTitle = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemJobTitle>(global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemJobTitle.CreateFromDiscriminatorValue); } },
                { "keywords", n => { Keywords = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemKeywords>(global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemKeywords.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "problems_solved", n => { ProblemsSolved = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "success_stories", n => { SuccessStories = n.GetStringValue(); } },
                { "usp", n => { Usp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("benefits", Benefits);
            writer.WriteCollectionOfPrimitiveValues<string>("company_size", CompanySize);
            writer.WriteCollectionOfPrimitiveValues<string>("customer_goals", CustomerGoals);
            writer.WriteCollectionOfPrimitiveValues<string>("industry", Industry);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemJobTitle>("job_title", JobTitle);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.AiAgentPayloadAnyOf2AiSdrConfigMemoryIcpsItemKeywords>("keywords", Keywords);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("problems_solved", ProblemsSolved);
            writer.WriteStringValue("success_stories", SuccessStories);
            writer.WriteStringValue("usp", Usp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
