// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>Type of action performed</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiSalesAgentActivityActionType
    {
        [EnumMember(Value = "create_campaign")]
        #pragma warning disable CS1591
        CreateCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "edit_campaign")]
        #pragma warning disable CS1591
        EditCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop_campaign")]
        #pragma warning disable CS1591
        StopCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause_campaign")]
        #pragma warning disable CS1591
        PauseCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "enrich_leads")]
        #pragma warning disable CS1591
        EnrichLeads,
        #pragma warning restore CS1591
        [EnumMember(Value = "push_lead")]
        #pragma warning disable CS1591
        PushLead,
        #pragma warning restore CS1591
        [EnumMember(Value = "recommend_lead")]
        #pragma warning disable CS1591
        RecommendLead,
        #pragma warning restore CS1591
        [EnumMember(Value = "warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "initial_setup_scrape")]
        #pragma warning disable CS1591
        InitialSetupScrape,
        #pragma warning restore CS1591
        [EnumMember(Value = "initial_setup_campaigns")]
        #pragma warning disable CS1591
        InitialSetupCampaigns,
        #pragma warning restore CS1591
        [EnumMember(Value = "initial_setup_enrich")]
        #pragma warning disable CS1591
        InitialSetupEnrich,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_sent")]
        #pragma warning disable CS1591
        EmailSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "lead_meeting_booked")]
        #pragma warning disable CS1591
        LeadMeetingBooked,
        #pragma warning restore CS1591
        [EnumMember(Value = "lead_closed")]
        #pragma warning disable CS1591
        LeadClosed,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_opened")]
        #pragma warning disable CS1591
        EmailOpened,
        #pragma warning restore CS1591
        [EnumMember(Value = "reply_received")]
        #pragma warning disable CS1591
        ReplyReceived,
        #pragma warning restore CS1591
        [EnumMember(Value = "opportunity_received")]
        #pragma warning disable CS1591
        OpportunityReceived,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_completed")]
        #pragma warning disable CS1591
        CampaignCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "imported_leads")]
        #pragma warning disable CS1591
        ImportedLeads,
        #pragma warning restore CS1591
    }
}
