// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BulkDeleteAgentItemsRequestItemsItemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ai_agent")]
        #pragma warning disable CS1591
        AiAgent,
        #pragma warning restore CS1591
        [EnumMember(Value = "automation")]
        #pragma warning disable CS1591
        Automation,
        #pragma warning restore CS1591
    }
}
