// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CountLeadsFromSupersearch429ResponseError
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Rate limit exceeded")]
        #pragma warning disable CS1591
        RateLimitExceeded,
        #pragma warning restore CS1591
    }
}
