// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1? CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1 CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2? CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3? CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3 CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4? CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4 CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5? CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5 CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItem();
            if("CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1 = new global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1();
            }
            else if("CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 = new global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2();
            }
            else if("CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3 = new global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1 != null)
            {
                return CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1.GetFieldDeserializers();
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 != null)
            {
                return CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2.GetFieldDeserializers();
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3 != null)
            {
                return CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3.GetFieldDeserializers();
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4 != null)
            {
                return CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4.GetFieldDeserializers();
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5 != null)
            {
                return CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1>(null, CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemBranch1);
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2>(null, CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2);
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3>(null, CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf3);
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4>(null, CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf4);
            }
            else if(CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5>(null, CreateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf5);
            }
        }
    }
}
#pragma warning restore CS0618
