// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>Type of the resource (1 for Campaign, 2 for List)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateAiEnrichment200ResponseResourceType
    {
        [EnumMember(Value = "CAMPAIGN")]
        #pragma warning disable CS1591
        Campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIST")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "1")]
        #pragma warning disable CS1591
        One,
        #pragma warning restore CS1591
        [EnumMember(Value = "2")]
        #pragma warning disable CS1591
        Two,
        #pragma warning restore CS1591
    }
}
