// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateInboxManagerAgentRequestGuidancesItemBasicGuidanceOptionsTone
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "friendly")]
        #pragma warning disable CS1591
        Friendly,
        #pragma warning restore CS1591
        [EnumMember(Value = "neutral")]
        #pragma warning disable CS1591
        Neutral,
        #pragma warning restore CS1591
        [EnumMember(Value = "matter_of_fact")]
        #pragma warning disable CS1591
        MatterOfFact,
        #pragma warning restore CS1591
        [EnumMember(Value = "professional")]
        #pragma warning disable CS1591
        Professional,
        #pragma warning restore CS1591
        [EnumMember(Value = "humorous")]
        #pragma warning disable CS1591
        Humorous,
        #pragma warning restore CS1591
    }
}
