// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Audience search filters in the SuperSearch format. Unknown keys are rejected: the search would otherwise silently ignore them and return unfiltered results. Enum values are matched literally, including spacing.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateLeadFinderAgentRequestSearchFilters : IParsable
    {
        /// <summary>Company-list audience boundary. Only completed lists owned by the caller workspace are accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyListId { get; set; }
#nullable restore
#else
        public string CompanyListId { get; set; }
#endif
        /// <summary>The company_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersCompanyName? CompanyName { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersCompanyName CompanyName { get; set; }
#endif
        /// <summary>The department property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersDepartmentItem?>? Department { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersDepartmentItem?> Department { get; set; }
#endif
        /// <summary>The domains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Domains { get; set; }
#nullable restore
#else
        public List<string> Domains { get; set; }
#endif
        /// <summary>Employee count filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersEmployeeCountItem>? EmployeeCount { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersEmployeeCountItem> EmployeeCount { get; set; }
#endif
        /// <summary>The funding_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItemEnum?>? Funding_type { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItemEnum?> Funding_type { get; set; }
#endif
        /// <summary>Product-UI alias of `funding_type`; both keys are accepted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItem?>? FundingType { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItem?> FundingType { get; set; }
#endif
        /// <summary>The industry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersIndustry? Industry { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersIndustry Industry { get; set; }
#endif
        /// <summary>Canonical filter for companies that are hiring for the specified job titles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? JobListing { get; set; }
#nullable restore
#else
        public List<string> JobListing { get; set; }
#endif
        /// <summary>Deprecated compatibility key for Job Listing filters. Use `jobListing` instead. Cannot be combined with `jobListing` on this endpoint.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? JobListingFilter { get; set; }
#nullable restore
#else
        public List<string> JobListingFilter { get; set; }
#endif
        /// <summary>The keyword_filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersKeywordFilter? KeywordFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersKeywordFilter KeywordFilter { get; set; }
#endif
        /// <summary>The level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLevelItem?>? Level { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLevelItem?> Level { get; set; }
#endif
        /// <summary>Whether to filter/display by contact location or company HQ location. Defaults to contact.</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocationModeEnum? Location_mode { get; set; }
        /// <summary>Product-UI alias of `location_mode`; both keys are accepted</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocationMode? LocationMode { get; set; }
        /// <summary>The locations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocations? Locations { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocations Locations { get; set; }
#endif
        /// <summary>If set, the lead finder will find companies that are similar to the look-alike domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Look_alike { get; set; }
#nullable restore
#else
        public string Look_alike { get; set; }
#endif
        /// <summary>Product-UI alias of `look_alike`; both keys are accepted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LookAlike { get; set; }
#nullable restore
#else
        public string LookAlike { get; set; }
#endif
        /// <summary>Deprecated. No longer written by the product UI; still accepted and forwarded so existing integrations keep working.</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLookAlikeMode? LookAlikeMode { get; set; }
        /// <summary>Names of the lead to include in the search</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Name { get; set; }
#nullable restore
#else
        public List<string> Name { get; set; }
#endif
        /// <summary>The news property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersNewsItem?>? News { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersNewsItem?> News { get; set; }
#endif
        /// <summary>The revenue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersRevenueItem?>? Revenue { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersRevenueItem?> Revenue { get; set; }
#endif
        /// <summary>If set, the lead finder will show only one lead per company</summary>
        public bool? ShowOneLeadPerCompany { get; set; }
        /// <summary>Filter leads by Autobound signal categories (e.g. job changes, traffic surges, LinkedIn activity). Leads matching ANY of the specified signals within the per-signal freshness window will be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSignalsItem>? Signals { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSignalsItem> Signals { get; set; }
#endif
        /// <summary>If set, the lead finder will skip leads that are owned by the user</summary>
        public bool? SkipOwnedLeads { get; set; }
        /// <summary>The subIndustry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSubIndustry? SubIndustry { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSubIndustry SubIndustry { get; set; }
#endif
        /// <summary>Technologies the lead company uses</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Technologies { get; set; }
#nullable restore
#else
        public List<string> Technologies { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersTitle? Title { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersTitle Title { get; set; }
#endif
        /// <summary>Restrict the search to companies that visited your website (requires a connected Website Visitors pixel). Combines with `domains` as an intersection.</summary>
        public bool? WebsiteVisitors { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company_list_id", n => { CompanyListId = n.GetStringValue(); } },
                { "company_name", n => { CompanyName = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersCompanyName>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersCompanyName.CreateFromDiscriminatorValue); } },
                { "department", n => { Department = n.GetCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersDepartmentItem>()?.AsList(); } },
                { "domains", n => { Domains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "employeeCount", n => { EmployeeCount = n.GetCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersEmployeeCountItem>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersEmployeeCountItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fundingType", n => { FundingType = n.GetCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItem>()?.AsList(); } },
                { "industry", n => { Industry = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersIndustry>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersIndustry.CreateFromDiscriminatorValue); } },
                { "jobListing", n => { JobListing = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "jobListingFilter", n => { JobListingFilter = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "keyword_filter", n => { KeywordFilter = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersKeywordFilter>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersKeywordFilter.CreateFromDiscriminatorValue); } },
                { "level", n => { Level = n.GetCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLevelItem>()?.AsList(); } },
                { "locationMode", n => { LocationMode = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocationMode>(); } },
                { "locations", n => { Locations = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocations>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocations.CreateFromDiscriminatorValue); } },
                { "lookAlike", n => { LookAlike = n.GetStringValue(); } },
                { "lookAlikeMode", n => { LookAlikeMode = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLookAlikeMode>(); } },
                { "name", n => { Name = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "news", n => { News = n.GetCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersNewsItem>()?.AsList(); } },
                { "revenue", n => { Revenue = n.GetCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersRevenueItem>()?.AsList(); } },
                { "show_one_lead_per_company", n => { ShowOneLeadPerCompany = n.GetBoolValue(); } },
                { "signals", n => { Signals = n.GetCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSignalsItem>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSignalsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "skip_owned_leads", n => { SkipOwnedLeads = n.GetBoolValue(); } },
                { "subIndustry", n => { SubIndustry = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSubIndustry>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSubIndustry.CreateFromDiscriminatorValue); } },
                { "technologies", n => { Technologies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "title", n => { Title = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersTitle>(global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersTitle.CreateFromDiscriminatorValue); } },
                { "website_visitors", n => { WebsiteVisitors = n.GetBoolValue(); } },
                { "funding_type", n => { Funding_type = n.GetCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItemEnum>()?.AsList(); } },
                { "location_mode", n => { Location_mode = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocationModeEnum>(); } },
                { "look_alike", n => { Look_alike = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("company_list_id", CompanyListId);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersCompanyName>("company_name", CompanyName);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersDepartmentItem>("department", Department);
            writer.WriteCollectionOfPrimitiveValues<string>("domains", Domains);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersEmployeeCountItem>("employeeCount", EmployeeCount);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItemEnum>("funding_type", Funding_type);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersFundingTypeItem>("fundingType", FundingType);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersIndustry>("industry", Industry);
            writer.WriteCollectionOfPrimitiveValues<string>("jobListing", JobListing);
            writer.WriteCollectionOfPrimitiveValues<string>("jobListingFilter", JobListingFilter);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersKeywordFilter>("keyword_filter", KeywordFilter);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLevelItem>("level", Level);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocationModeEnum>("location_mode", Location_mode);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocationMode>("locationMode", LocationMode);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLocations>("locations", Locations);
            writer.WriteStringValue("look_alike", Look_alike);
            writer.WriteStringValue("lookAlike", LookAlike);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersLookAlikeMode>("lookAlikeMode", LookAlikeMode);
            writer.WriteCollectionOfPrimitiveValues<string>("name", Name);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersNewsItem>("news", News);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersRevenueItem>("revenue", Revenue);
            writer.WriteBoolValue("show_one_lead_per_company", ShowOneLeadPerCompany);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSignalsItem>("signals", Signals);
            writer.WriteBoolValue("skip_owned_leads", SkipOwnedLeads);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersSubIndustry>("subIndustry", SubIndustry);
            writer.WriteCollectionOfPrimitiveValues<string>("technologies", Technologies);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.CreateLeadFinderAgentRequestSearchFiltersTitle>("title", Title);
            writer.WriteBoolValue("website_visitors", WebsiteVisitors);
        }
    }
}
#pragma warning restore CS0618
