// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>Method used to upload the lead</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Def11_upload_method
    {
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "website-visitor")]
        #pragma warning disable CS1591
        WebsiteVisitor,
        #pragma warning restore CS1591
    }
}
