// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>Less than or equal operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrichLeadsFromSupersearchRequestSearchFiltersEmployeeCountItemOneOf3Op
    {
        [EnumMember(Value = "lte")]
        #pragma warning disable CS1591
        Lte,
        #pragma warning restore CS1591
    }
}
