// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Raw sending status data. Some fields may be missing when campaign is out of schedule.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetCampaignSendingStatus200ResponseDiagnostics : IAdditionalDataHolder, IParsable
    {
        /// <summary>Summary of sending account availability. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsAccountsSummary? AccountsSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsAccountsSummary AccountsSummary { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Campaign daily sending limit status. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsCampaignDailyLimit? CampaignDailyLimit { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsCampaignDailyLimit CampaignDailyLimit { get; set; }
#endif
        /// <summary>The campaign ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>Per-domain sending limit status. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsDomainLimiter? DomainLimiter { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsDomainLimiter DomainLimiter { get; set; }
#endif
        /// <summary>ESP routing status. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsEspRoutingStatus? EspRoutingStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsEspRoutingStatus EspRoutingStatus { get; set; }
#endif
        /// <summary>Follow-up emails waiting status. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsFollowUpsWaiting? FollowUpsWaiting { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsFollowUpsWaiting FollowUpsWaiting { get; set; }
#endif
        /// <summary>Tracks persistence of the current issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsIssueTracking? IssueTracking { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsIssueTracking IssueTracking { get; set; }
#endif
        /// <summary>ISO timestamp of when this data was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdated { get; set; }
#nullable restore
#else
        public string LastUpdated { get; set; }
#endif
        /// <summary>Lead availability status. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsLeadsStatus? LeadsStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsLeadsStatus LeadsStatus { get; set; }
#endif
        /// <summary>New lead daily limit status. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsNewLeadLimit? NewLeadLimit { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsNewLeadLimit NewLeadLimit { get; set; }
#endif
        /// <summary>Campaign schedule status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsScheduleStatus? ScheduleStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsScheduleStatus ScheduleStatus { get; set; }
#endif
        /// <summary>Send one-by-one settings. May be missing when campaign is out of schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsSendOneByOne? SendOneByOne { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsSendOneByOne SendOneByOne { get; set; }
#endif
        /// <summary>Status code explaining why the campaign is not sending or sending slower</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsStatus? Status { get; set; }
        /// <summary>The subsequence ID (only present for subsequence endpoints)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubsequenceId { get; set; }
#nullable restore
#else
        public string SubsequenceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnostics"/> and sets the default values.
        /// </summary>
        public GetCampaignSendingStatus200ResponseDiagnostics()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnostics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnostics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnostics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts_summary", n => { AccountsSummary = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsAccountsSummary>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsAccountsSummary.CreateFromDiscriminatorValue); } },
                { "campaign_daily_limit", n => { CampaignDailyLimit = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsCampaignDailyLimit>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsCampaignDailyLimit.CreateFromDiscriminatorValue); } },
                { "campaign_id", n => { CampaignId = n.GetStringValue(); } },
                { "domain_limiter", n => { DomainLimiter = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsDomainLimiter>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsDomainLimiter.CreateFromDiscriminatorValue); } },
                { "esp_routing_status", n => { EspRoutingStatus = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsEspRoutingStatus>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsEspRoutingStatus.CreateFromDiscriminatorValue); } },
                { "follow_ups_waiting", n => { FollowUpsWaiting = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsFollowUpsWaiting>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsFollowUpsWaiting.CreateFromDiscriminatorValue); } },
                { "issue_tracking", n => { IssueTracking = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsIssueTracking>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsIssueTracking.CreateFromDiscriminatorValue); } },
                { "last_updated", n => { LastUpdated = n.GetStringValue(); } },
                { "leads_status", n => { LeadsStatus = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsLeadsStatus>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsLeadsStatus.CreateFromDiscriminatorValue); } },
                { "new_lead_limit", n => { NewLeadLimit = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsNewLeadLimit>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsNewLeadLimit.CreateFromDiscriminatorValue); } },
                { "schedule_status", n => { ScheduleStatus = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsScheduleStatus>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsScheduleStatus.CreateFromDiscriminatorValue); } },
                { "send_one_by_one", n => { SendOneByOne = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsSendOneByOne>(global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsSendOneByOne.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsStatus>(); } },
                { "subsequence_id", n => { SubsequenceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsAccountsSummary>("accounts_summary", AccountsSummary);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsCampaignDailyLimit>("campaign_daily_limit", CampaignDailyLimit);
            writer.WriteStringValue("campaign_id", CampaignId);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsDomainLimiter>("domain_limiter", DomainLimiter);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsEspRoutingStatus>("esp_routing_status", EspRoutingStatus);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsFollowUpsWaiting>("follow_ups_waiting", FollowUpsWaiting);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsIssueTracking>("issue_tracking", IssueTracking);
            writer.WriteStringValue("last_updated", LastUpdated);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsLeadsStatus>("leads_status", LeadsStatus);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsNewLeadLimit>("new_lead_limit", NewLeadLimit);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsScheduleStatus>("schedule_status", ScheduleStatus);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsSendOneByOne>("send_one_by_one", SendOneByOne);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.GetCampaignSendingStatus200ResponseDiagnosticsStatus>("status", Status);
            writer.WriteStringValue("subsequence_id", SubsequenceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
