// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetDeliverabilityAgentState200ResponseCurrentActivity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityActive? Active { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityActive Active { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completed_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityCompletedSummary? CompletedSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityCompletedSummary CompletedSummary { get; set; }
#endif
        /// <summary>The queued property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityQueuedItem>? Queued { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityQueuedItem> Queued { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivity"/> and sets the default values.
        /// </summary>
        public GetDeliverabilityAgentState200ResponseCurrentActivity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityActive>(global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityActive.CreateFromDiscriminatorValue); } },
                { "completed_summary", n => { CompletedSummary = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityCompletedSummary>(global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityCompletedSummary.CreateFromDiscriminatorValue); } },
                { "queued", n => { Queued = n.GetCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityQueuedItem>(global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityQueuedItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityActive>("active", Active);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityCompletedSummary>("completed_summary", CompletedSummary);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentState200ResponseCurrentActivityQueuedItem>("queued", Queued);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
