// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetDeliverabilityAgentStateById200ResponseRunSummaryLatest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestChecksItem>? Checks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestChecksItem> Checks { get; set; }
#endif
        /// <summary>The completed_at property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The completed_checks property</summary>
        public double? CompletedChecks { get; set; }
        /// <summary>The cycle_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CycleId { get; set; }
#nullable restore
#else
        public string CycleId { get; set; }
#endif
        /// <summary>The failed_count property</summary>
        public double? FailedCount { get; set; }
        /// <summary>The feed_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestFeedItemsItem>? FeedItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestFeedItemsItem> FeedItems { get; set; }
#endif
        /// <summary>The healthy_count property</summary>
        public double? HealthyCount { get; set; }
        /// <summary>The info_count property</summary>
        public double? InfoCount { get; set; }
        /// <summary>The needs_attention_count property</summary>
        public double? NeedsAttentionCount { get; set; }
        /// <summary>The started_at property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestStatus? Status { get; set; }
        /// <summary>The total_checks property</summary>
        public double? TotalChecks { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatest"/> and sets the default values.
        /// </summary>
        public GetDeliverabilityAgentStateById200ResponseRunSummaryLatest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checks", n => { Checks = n.GetCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestChecksItem>(global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestChecksItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "completed_checks", n => { CompletedChecks = n.GetDoubleValue(); } },
                { "cycle_id", n => { CycleId = n.GetStringValue(); } },
                { "failed_count", n => { FailedCount = n.GetDoubleValue(); } },
                { "feed_items", n => { FeedItems = n.GetCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestFeedItemsItem>(global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestFeedItemsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "healthy_count", n => { HealthyCount = n.GetDoubleValue(); } },
                { "info_count", n => { InfoCount = n.GetDoubleValue(); } },
                { "needs_attention_count", n => { NeedsAttentionCount = n.GetDoubleValue(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestStatus>(); } },
                { "total_checks", n => { TotalChecks = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestChecksItem>("checks", Checks);
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteDoubleValue("completed_checks", CompletedChecks);
            writer.WriteStringValue("cycle_id", CycleId);
            writer.WriteDoubleValue("failed_count", FailedCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestFeedItemsItem>("feed_items", FeedItems);
            writer.WriteDoubleValue("healthy_count", HealthyCount);
            writer.WriteDoubleValue("info_count", InfoCount);
            writer.WriteDoubleValue("needs_attention_count", NeedsAttentionCount);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.GetDeliverabilityAgentStateById200ResponseRunSummaryLatestStatus>("status", Status);
            writer.WriteDoubleValue("total_checks", TotalChecks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
