// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetInboxPlacementTest200ResponseAutomationsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Actions to take when condition is met</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemThen? Then { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemThen Then { get; set; }
#endif
        /// <summary>The when property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemWhen? When { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemWhen When { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItem"/> and sets the default values.
        /// </summary>
        public GetInboxPlacementTest200ResponseAutomationsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "then", n => { Then = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemThen>(global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemThen.CreateFromDiscriminatorValue); } },
                { "when", n => { When = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemWhen>(global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemWhen.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemThen>("then", Then);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetInboxPlacementTest200ResponseAutomationsItemWhen>("when", When);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
