// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetSalesAgentOpportunitySummary200ResponseSummary : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The breakdown property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummaryBreakdown? Breakdown { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummaryBreakdown Breakdown { get; set; }
#endif
        /// <summary>The total_opportunities property</summary>
        public double? TotalOpportunities { get; set; }
        /// <summary>The total_value property</summary>
        public double? TotalValue { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummary"/> and sets the default values.
        /// </summary>
        public GetSalesAgentOpportunitySummary200ResponseSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "breakdown", n => { Breakdown = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummaryBreakdown>(global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummaryBreakdown.CreateFromDiscriminatorValue); } },
                { "total_opportunities", n => { TotalOpportunities = n.GetDoubleValue(); } },
                { "total_value", n => { TotalValue = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.GetSalesAgentOpportunitySummary200ResponseSummaryBreakdown>("breakdown", Breakdown);
            writer.WriteDoubleValue("total_opportunities", TotalOpportunities);
            writer.WriteDoubleValue("total_value", TotalValue);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
