// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>The ID of the Instantly Credits plan subscribed to</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetWorkspacePlanDetails200ResponseSubscriptionsCreditsProductId
    {
        [EnumMember(Value = "pid_nic_v1")]
        #pragma warning disable CS1591
        PidNicV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_nic_v1_annual")]
        #pragma warning disable CS1591
        PidNicV1Annual,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_gic_v1")]
        #pragma warning disable CS1591
        PidGicV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_gic_v1_annual")]
        #pragma warning disable CS1591
        PidGicV1Annual,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_sic_v1")]
        #pragma warning disable CS1591
        PidSicV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_sic_v1_annual")]
        #pragma warning disable CS1591
        PidSicV1Annual,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_hic_v1")]
        #pragma warning disable CS1591
        PidHicV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "pid_hic_v1_annual")]
        #pragma warning disable CS1591
        PidHicV1Annual,
        #pragma warning restore CS1591
    }
}
