// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>The type of product subscribed to</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetWorkspaceSubscriptionDetails200ResponseSubscriptionsItemProductType
    {
        [EnumMember(Value = "prt_outreach")]
        #pragma warning disable CS1591
        PrtOutreach,
        #pragma warning restore CS1591
        [EnumMember(Value = "prt_leadfinder")]
        #pragma warning disable CS1591
        PrtLeadfinder,
        #pragma warning restore CS1591
    }
}
