// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListSalesAgentLeadActivityFilterParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "replied")]
        #pragma warning disable CS1591
        Replied,
        #pragma warning restore CS1591
        [EnumMember(Value = "has_opportunity")]
        #pragma warning disable CS1591
        HasOpportunity,
        #pragma warning restore CS1591
    }
}
