// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListLeadsRequestQueriesItemValuesOccurrenceCountCondition
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "more")]
        #pragma warning disable CS1591
        More,
        #pragma warning restore CS1591
        [EnumMember(Value = "less")]
        #pragma warning disable CS1591
        Less,
        #pragma warning restore CS1591
        [EnumMember(Value = "equal")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
    }
}
