// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Configuration for the AI Sales Agent including memory, enrichment settings, outreach settings, and autonomy settings. If not provided, default configuration will be used.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchAiAgentRequestConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Settings for AI Sales Agent autonomy including autopilot_mode, auto_reply_to_responses, and manual_leads_mode</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigAutonomySettings? AutonomySettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigAutonomySettings AutonomySettings { get; set; }
#endif
        /// <summary>Settings for lead enrichment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigEnrichmentSettings? EnrichmentSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigEnrichmentSettings EnrichmentSettings { get; set; }
#endif
        /// <summary>Investment details for investment agents, describing the investment thesis and target companies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvestmentDetails { get; set; }
#nullable restore
#else
        public string InvestmentDetails { get; set; }
#endif
        /// <summary>Business context and memory for the AI Sales Agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigMemory? Memory { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigMemory Memory { get; set; }
#endif
        /// <summary>Settings for email outreach including campaign_schedule, email_list, email_tag_list, daily_limit, stop_on_reply, open_tracking, first_email_text_only, prioritize_new_leads, match_lead_esp</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigOutreachSettings? OutreachSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigOutreachSettings OutreachSettings { get; set; }
#endif
        /// <summary>Partnership details for partnership agents, describing the partnership goals and target partners</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartnershipDetails { get; set; }
#nullable restore
#else
        public string PartnershipDetails { get; set; }
#endif
        /// <summary>Position details for recruiting agents, describing the role, responsibilities, and requirements</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PositionDetails { get; set; }
#nullable restore
#else
        public string PositionDetails { get; set; }
#endif
        /// <summary>Research details for user research agents, describing the research goals and target participants</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResearchDetails { get; set; }
#nullable restore
#else
        public string ResearchDetails { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfig"/> and sets the default values.
        /// </summary>
        public PatchAiAgentRequestConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autonomy_settings", n => { AutonomySettings = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigAutonomySettings>(global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigAutonomySettings.CreateFromDiscriminatorValue); } },
                { "enrichment_settings", n => { EnrichmentSettings = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigEnrichmentSettings>(global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigEnrichmentSettings.CreateFromDiscriminatorValue); } },
                { "investment_details", n => { InvestmentDetails = n.GetStringValue(); } },
                { "memory", n => { Memory = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigMemory>(global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigMemory.CreateFromDiscriminatorValue); } },
                { "outreach_settings", n => { OutreachSettings = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigOutreachSettings>(global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigOutreachSettings.CreateFromDiscriminatorValue); } },
                { "partnership_details", n => { PartnershipDetails = n.GetStringValue(); } },
                { "position_details", n => { PositionDetails = n.GetStringValue(); } },
                { "research_details", n => { ResearchDetails = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigAutonomySettings>("autonomy_settings", AutonomySettings);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigEnrichmentSettings>("enrichment_settings", EnrichmentSettings);
            writer.WriteStringValue("investment_details", InvestmentDetails);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigMemory>("memory", Memory);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestConfigOutreachSettings>("outreach_settings", OutreachSettings);
            writer.WriteStringValue("partnership_details", PartnershipDetails);
            writer.WriteStringValue("position_details", PositionDetails);
            writer.WriteStringValue("research_details", ResearchDetails);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
