// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The days property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemDays? Days { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemDays Days { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The timing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemTiming? Timing { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemTiming Timing { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItem"/> and sets the default values.
        /// </summary>
        public PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "days", n => { Days = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemDays>(global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemDays.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "timing", n => { Timing = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemTiming>(global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemTiming.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemDays>("days", Days);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.PatchAiAgentRequestPayloadAiSdrConfigOutreachSettingsCampaignScheduleSchedulesItemTiming>("timing", Timing);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
