// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ToggleTagResource_filterMember1 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The filter property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.ToggleTagResource_filterMember1_filter? Filter { get; set; }
        /// <summary>The search property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Search { get; set; }
#nullable restore
#else
        public string Search { get; set; }
#endif
        /// <summary>The tag_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.UnionBranch? TagId { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.UnionBranch TagId { get; set; }
#endif
        /// <summary>The tag_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TagIds { get; set; }
#nullable restore
#else
        public List<Guid?> TagIds { get; set; }
#endif
        /// <summary>The tag_ids_all property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TagIdsAll { get; set; }
#nullable restore
#else
        public List<Guid?> TagIdsAll { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.ToggleTagResource_filterMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.ToggleTagResource_filterMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.ToggleTagResource_filterMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filter", n => { Filter = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.ToggleTagResource_filterMember1_filter>(); } },
                { "search", n => { Search = n.GetStringValue(); } },
                { "tag_id", n => { TagId = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UnionBranch>(global::Soenneker.Instantly.OpenApiClient.Models.UnionBranch.CreateFromDiscriminatorValue); } },
                { "tag_ids", n => { TagIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "tag_ids_all", n => { TagIdsAll = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.ToggleTagResource_filterMember1_filter>("filter", Filter);
            writer.WriteStringValue("search", Search);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UnionBranch>("tag_id", TagId);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("tag_ids", TagIds);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("tag_ids_all", TagIdsAll);
        }
    }
}
#pragma warning restore CS0618
