// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Employee count greater-than-or-equal range
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 : IParsable
    {
        /// <summary>Deprecated opposite bound accepted for compatibility and removed during normalization.</summary>
        public double? Max { get; set; }
        /// <summary>Minimum employee count (inclusive).</summary>
        public double? Min { get; set; }
        /// <summary>Greater than or equal operation.</summary>
        public global::Soenneker.Instantly.OpenApiClient.Models.GteOp? Op { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestFallbackSearchFiltersEmployeeCountItemOneOf2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max", n => { Max = n.GetDoubleValue(); } },
                { "min", n => { Min = n.GetDoubleValue(); } },
                { "op", n => { Op = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.GteOp>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("max", Max);
            writer.WriteDoubleValue("min", Min);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Models.GteOp>("op", Op);
        }
    }
}
#pragma warning restore CS0618
