// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>How included titles are matched. Defaults to CONTAINS.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateSavedSearchRequestSearchFiltersTitleIncludeMode
    {
        [EnumMember(Value = "EXACT")]
        #pragma warning disable CS1591
        Exact,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTAINS")]
        #pragma warning disable CS1591
        Contains,
        #pragma warning restore CS1591
    }
}
