// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4"/>, <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1? UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1 UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2? UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2 UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3? UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3 UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4? UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4 UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5? UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5 UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItem();
            if("UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1 = new global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1();
            }
            else if("UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2 = new global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2();
            }
            else if("UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3 = new global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1 != null)
            {
                return UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1.GetFieldDeserializers();
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2 != null)
            {
                return UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2.GetFieldDeserializers();
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3 != null)
            {
                return UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3.GetFieldDeserializers();
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4 != null)
            {
                return UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4.GetFieldDeserializers();
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5 != null)
            {
                return UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1>(null, UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemBranch1);
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2>(null, UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf2);
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3>(null, UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf3);
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4>(null, UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf4);
            }
            else if(UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Models.UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5>(null, UpdateLeadFinderAgentRequestSearchFiltersEmployeeCountItemOneOf5);
            }
        }
    }
}
#pragma warning restore CS0618
