// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Analytics;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Guidances;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Replies;
using Soenneker.Instantly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ai-agents\inbox-manager\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InboxManagerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The analytics property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Analytics.AnalyticsRequestBuilder Analytics
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Analytics.AnalyticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The guidances property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Guidances.GuidancesRequestBuilder Guidances
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Guidances.GuidancesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replies property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Replies.RepliesRequestBuilder Replies
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.Replies.RepliesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InboxManagerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/inbox-manager/{id}{?with_metadata*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InboxManagerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/inbox-manager/{id}{?with_metadata*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a single AI Inbox Manager with its full configuration.Requires one of the following scopes: `ai_agents:read`, `ai_agents:all`, `all:read`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager?> GetAsync(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder.InboxManagerItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager> GetAsync(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder.InboxManagerItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent402Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.GetInboxManagerAgent429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update an AI Inbox Manager, including its configuration.Requires one of the following scopes: `ai_agents:update`, `ai_agents:all`, `all:update`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager?> PatchAsync(global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager> PatchAsync(global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent402Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgent429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.AiInboxManager.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a single AI Inbox Manager with its full configuration.Requires one of the following scopes: `ai_agents:read`, `ai_agents:all`, `all:read`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder.InboxManagerItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder.InboxManagerItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update an AI Inbox Manager, including its configuration.Requires one of the following scopes: `ai_agents:update`, `ai_agents:all`, `all:update`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Instantly.OpenApiClient.Models.PatchInboxManagerAgentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.InboxManager.Item.InboxManagerItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a single AI Inbox Manager with its full configuration.Requires one of the following scopes: `ai_agents:read`, `ai_agents:all`, `all:read`, `all:all`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InboxManagerItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Whether to include additional metadata about the ai agent</summary>
            [QueryParameter("with_metadata")]
            public bool? WithMetadata { get; set; }
        }
    }
}
#pragma warning restore CS0618
