// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.DfyEmailAccountOrders.Domains.Check
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Check404Error_error
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Not Found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
    }
}
