// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.Complete;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.PauseAffectedAccounts;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.PauseCampaignSending;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ai-agents\deliverability\feed-items\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FeedItemsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The complete property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.Complete.CompleteRequestBuilder Complete
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.Complete.CompleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pauseAffectedAccounts property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.PauseAffectedAccounts.PauseAffectedAccountsRequestBuilder PauseAffectedAccounts
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.PauseAffectedAccounts.PauseAffectedAccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pauseCampaignSending property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.PauseCampaignSending.PauseCampaignSendingRequestBuilder PauseCampaignSending
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.PauseCampaignSending.PauseCampaignSendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.FeedItemsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeedItemsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/deliverability/feed-items/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Deliverability.FeedItems.Item.FeedItemsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeedItemsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/deliverability/feed-items/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
