// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.InboxPlacementAnalytics.StatsByTestId
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatsByTestIdPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateFrom { get; set; }
#nullable restore
#else
        public string DateFrom { get; set; }
#endif
        /// <summary>The date_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTo { get; set; }
#nullable restore
#else
        public string DateTo { get; set; }
#endif
        /// <summary>The recipient_esp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? RecipientEsp { get; set; }
#nullable restore
#else
        public List<double?> RecipientEsp { get; set; }
#endif
        /// <summary>The recipient_geo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? RecipientGeo { get; set; }
#nullable restore
#else
        public List<double?> RecipientGeo { get; set; }
#endif
        /// <summary>The recipient_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? RecipientType { get; set; }
#nullable restore
#else
        public List<double?> RecipientType { get; set; }
#endif
        /// <summary>The sender_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderEmail { get; set; }
#nullable restore
#else
        public string SenderEmail { get; set; }
#endif
        /// <summary>The test_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TestIds { get; set; }
#nullable restore
#else
        public List<Guid?> TestIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.InboxPlacementAnalytics.StatsByTestId.StatsByTestIdPostRequestBody"/> and sets the default values.
        /// </summary>
        public StatsByTestIdPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.InboxPlacementAnalytics.StatsByTestId.StatsByTestIdPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Api.V2.InboxPlacementAnalytics.StatsByTestId.StatsByTestIdPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.InboxPlacementAnalytics.StatsByTestId.StatsByTestIdPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date_from", n => { DateFrom = n.GetStringValue(); } },
                { "date_to", n => { DateTo = n.GetStringValue(); } },
                { "recipient_esp", n => { RecipientEsp = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "recipient_geo", n => { RecipientGeo = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "recipient_type", n => { RecipientType = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "sender_email", n => { SenderEmail = n.GetStringValue(); } },
                { "test_ids", n => { TestIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("date_from", DateFrom);
            writer.WriteStringValue("date_to", DateTo);
            writer.WriteCollectionOfPrimitiveValues<double?>("recipient_esp", RecipientEsp);
            writer.WriteCollectionOfPrimitiveValues<double?>("recipient_geo", RecipientGeo);
            writer.WriteCollectionOfPrimitiveValues<double?>("recipient_type", RecipientType);
            writer.WriteStringValue("sender_email", SenderEmail);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("test_ids", TestIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
