// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails
{
    /// <summary>The billing interval of the subscription</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionDetailsGetResponse_subscriptions_interval
    {
        [EnumMember(Value = "month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
        [EnumMember(Value = "year")]
        #pragma warning disable CS1591
        Year,
        #pragma warning restore CS1591
    }
}
