// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubscriptionDetailsGetResponse_subscriptions : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unix timestamp when the subscription will be canceled, null if not scheduled for cancellation</summary>
        public double? CancelAtTime { get; set; }
        /// <summary>Unix timestamp when the current billing period ends</summary>
        public double? CurrentPeriodEnd { get; set; }
        /// <summary>The billing interval of the subscription</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_interval? Interval { get; set; }
        /// <summary>The type of plan - either primary plan or addon</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_plan_type? PlanType { get; set; }
        /// <summary>The Stripe price ID associated with this subscription</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PriceId { get; set; }
#nullable restore
#else
        public string PriceId { get; set; }
#endif
        /// <summary>The price of the subscription in dollars</summary>
        public double? PriceInDollars { get; set; }
        /// <summary>The Id of outreach plan subscribed to</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_product_id? ProductId { get; set; }
        /// <summary>The type of product subscribed to</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_product_type? ProductType { get; set; }
        /// <summary>The quantity of subscribed items</summary>
        public double? Quantity { get; set; }
        /// <summary>The ID of the workspace</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions"/> and sets the default values.
        /// </summary>
        public SubscriptionDetailsGetResponse_subscriptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cancel_at_time", n => { CancelAtTime = n.GetDoubleValue(); } },
                { "current_period_end", n => { CurrentPeriodEnd = n.GetDoubleValue(); } },
                { "interval", n => { Interval = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_interval>(); } },
                { "plan_type", n => { PlanType = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_plan_type>(); } },
                { "price_id", n => { PriceId = n.GetStringValue(); } },
                { "price_in_dollars", n => { PriceInDollars = n.GetDoubleValue(); } },
                { "product_id", n => { ProductId = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_product_id>(); } },
                { "product_type", n => { ProductType = n.GetEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_product_type>(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("cancel_at_time", CancelAtTime);
            writer.WriteDoubleValue("current_period_end", CurrentPeriodEnd);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_interval>("interval", Interval);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_plan_type>("plan_type", PlanType);
            writer.WriteStringValue("price_id", PriceId);
            writer.WriteDoubleValue("price_in_dollars", PriceInDollars);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_product_id>("product_id", ProductId);
            writer.WriteEnumValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.SubscriptionDetails.SubscriptionDetailsGetResponse_subscriptions_product_type>("product_type", ProductType);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteGuidValue("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
