// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Sales.Item.Leads.Item.Research;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Sales.Item.Leads.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ai-agents\sales\{id}\leads\{leadId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLeadItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The research property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Sales.Item.Leads.Item.Research.ResearchRequestBuilder Research
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Sales.Item.Leads.Item.Research.ResearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Sales.Item.Leads.Item.WithLeadItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLeadItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/sales/{id}/leads/{leadId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.AiAgents.Sales.Item.Leads.Item.WithLeadItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLeadItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ai-agents/sales/{id}/leads/{leadId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
