// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.PlanDetails;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\workspace-billing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspaceBillingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The planDetails property</summary>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.PlanDetails.PlanDetailsRequestBuilder PlanDetails
        {
            get => new global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.PlanDetails.PlanDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.WorkspaceBillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspaceBillingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/workspace-billing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceBilling.WorkspaceBillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspaceBillingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/workspace-billing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
