// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Instantly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.Domains.Item.Forwarding
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\domains\{domain}\forwarding
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForwardingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.Domains.Item.Forwarding.ForwardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/domains/{domain}/forwarding", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.Domains.Item.Forwarding.ForwardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/domains/{domain}/forwarding", rawUrl)
        {
        }
        /// <summary>
        /// Removes web forwarding from a domain ordered through Instantly. This operation is idempotent: removing forwarding from a domain that has none configured succeeds without changes. This request has a rate limit of 10 requests per minute, or 60 requests per hour.Requires one of the following scopes: `dfy_email_account_orders:delete`, `dfy_email_account_orders:all`, `all:delete`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding502Response">When receiving a 502 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding402Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding409Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding429Response.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.Instantly.OpenApiClient.Models.DeleteDomainForwarding502Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the stored web forwarding configuration for a domain ordered through Instantly. All fields except `domain` are null when no forwarding is configured.Requires one of the following scopes: `dfy_email_account_orders:read`, `dfy_email_account_orders:all`, `all:read`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding402Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.GetDomainForwarding429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Sets web forwarding on a domain ordered through Instantly. The forwarding domain must be a valid domain different from the domain itself. Returns a conflict error while the domain order is still being provisioned, and an unprocessable entity error when the requested forwarding configuration is not supported for the domain. This request has a rate limit of 10 requests per minute, or 60 requests per hour.Requires one of the following scopes: `dfy_email_account_orders:update`, `dfy_email_account_orders:all`, `all:update`, `all:all`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding502Response">When receiving a 502 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding?> PutAsync(global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwardingRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding> PutAsync(global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwardingRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding402Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding409Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding429Response.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwarding502Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding>(requestInfo, global::Soenneker.Instantly.OpenApiClient.Models.DomainForwarding.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Removes web forwarding from a domain ordered through Instantly. This operation is idempotent: removing forwarding from a domain that has none configured succeeds without changes. This request has a rate limit of 10 requests per minute, or 60 requests per hour.Requires one of the following scopes: `dfy_email_account_orders:delete`, `dfy_email_account_orders:all`, `all:delete`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns the stored web forwarding configuration for a domain ordered through Instantly. All fields except `domain` are null when no forwarding is configured.Requires one of the following scopes: `dfy_email_account_orders:read`, `dfy_email_account_orders:all`, `all:read`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Sets web forwarding on a domain ordered through Instantly. The forwarding domain must be a valid domain different from the domain itself. Returns a conflict error while the domain order is still being provisioned, and an unprocessable entity error when the requested forwarding configuration is not supported for the domain. This request has a rate limit of 10 requests per minute, or 60 requests per hour.Requires one of the following scopes: `dfy_email_account_orders:update`, `dfy_email_account_orders:all`, `all:update`, `all:all`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwardingRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Instantly.OpenApiClient.Models.UpdateDomainForwardingRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.Domains.Item.Forwarding.ForwardingRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.Domains.Item.Forwarding.ForwardingRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.Domains.Item.Forwarding.ForwardingRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
