// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.WorkspaceMembers
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkspaceMembersPostRequestBody_permissions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DASHBOARD_VIEW")]
        #pragma warning disable CS1591
        DASHBOARD_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAMPAIGNS_VIEW")]
        #pragma warning disable CS1591
        CAMPAIGNS_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAMPAIGNS_CREATE")]
        #pragma warning disable CS1591
        CAMPAIGNS_CREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAMPAIGNS_EDIT")]
        #pragma warning disable CS1591
        CAMPAIGNS_EDIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAMPAIGNS_DELETE")]
        #pragma warning disable CS1591
        CAMPAIGNS_DELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION_MANAGE")]
        #pragma warning disable CS1591
        ORGANIZATION_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION_INTEGRATIONS")]
        #pragma warning disable CS1591
        ORGANIZATION_INTEGRATIONS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION_BILLING")]
        #pragma warning disable CS1591
        ORGANIZATION_BILLING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION_USERS_MANAGE")]
        #pragma warning disable CS1591
        ORGANIZATION_USERS_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEAD_FINDER_VIEW")]
        #pragma warning disable CS1591
        LEAD_FINDER_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_LEAD_LABELS_CREATE")]
        #pragma warning disable CS1591
        CUSTOM_LEAD_LABELS_CREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_LEAD_LABELS_EDIT")]
        #pragma warning disable CS1591
        CUSTOM_LEAD_LABELS_EDIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_LEAD_LABELS_DELETE")]
        #pragma warning disable CS1591
        CUSTOM_LEAD_LABELS_DELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNIBOX_ALL")]
        #pragma warning disable CS1591
        UNIBOX_ALL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ANALYTICS_READ")]
        #pragma warning disable CS1591
        ANALYTICS_READ,
        #pragma warning restore CS1591
        [EnumMember(Value = "AGENCY_MANAGE")]
        #pragma warning disable CS1591
        AGENCY_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNTS_VIEW")]
        #pragma warning disable CS1591
        ACCOUNTS_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNTS_MANAGE")]
        #pragma warning disable CS1591
        ACCOUNTS_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEAD_MANAGEMENT_VIEW")]
        #pragma warning disable CS1591
        LEAD_MANAGEMENT_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEADS_MOVE")]
        #pragma warning disable CS1591
        LEADS_MOVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRM_VIEW")]
        #pragma warning disable CS1591
        CRM_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBSITE_VISITORS_VIEW")]
        #pragma warning disable CS1591
        WEBSITE_VISITORS_VIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "BLOCKLIST_MANAGE")]
        #pragma warning disable CS1591
        BLOCKLIST_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREFERENCES_MANAGE")]
        #pragma warning disable CS1591
        PREFERENCES_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INBOX_PLACEMENT_MANAGE")]
        #pragma warning disable CS1591
        INBOX_PLACEMENT_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "AI_AGENTS_MANAGE")]
        #pragma warning disable CS1591
        AI_AGENTS_MANAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKSPACE_GROUP_MEMBERS_INVITE")]
        #pragma warning disable CS1591
        WORKSPACE_GROUP_MEMBERS_INVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKSPACE_GROUP_MEMBERS_REMOVE")]
        #pragma warning disable CS1591
        WORKSPACE_GROUP_MEMBERS_REMOVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKSPACE_GROUP_MEMBERS_LEAVE")]
        #pragma warning disable CS1591
        WORKSPACE_GROUP_MEMBERS_LEAVE,
        #pragma warning restore CS1591
    }
}
