// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithResource_GetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether leads added to the list will be automatically enriched</summary>
        public bool? AutoUpdate { get; set; }
        /// <summary>Enrichment types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_enrichment_payload? EnrichmentPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_enrichment_payload EnrichmentPayload { get; set; }
#endif
        /// <summary>Whether the enrichment exists</summary>
        public bool? Exists { get; set; }
        /// <summary>Whether the enrichment for this resource returned no leads for these search filters. This is only applicable for enrichments created from SuperSearch.</summary>
        public bool? HasNoLeads { get; set; }
        /// <summary>Whether the enrichment is in progress</summary>
        public bool? InProgress { get; set; }
        /// <summary>Whether the enrichment is evergreen</summary>
        public bool? IsEvergreen { get; set; }
        /// <summary>ID of the resource being enriched</summary>
        public Guid? ResourceId { get; set; }
        /// <summary>Search filters used to create this enrichment (only present for enrichments created from SuperSearch)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_search_filters? SearchFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_search_filters SearchFilters { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_update", n => { AutoUpdate = n.GetBoolValue(); } },
                { "enrichment_payload", n => { EnrichmentPayload = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_enrichment_payload>(global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_enrichment_payload.CreateFromDiscriminatorValue); } },
                { "exists", n => { Exists = n.GetBoolValue(); } },
                { "has_no_leads", n => { HasNoLeads = n.GetBoolValue(); } },
                { "in_progress", n => { InProgress = n.GetBoolValue(); } },
                { "is_evergreen", n => { IsEvergreen = n.GetBoolValue(); } },
                { "resource_id", n => { ResourceId = n.GetGuidValue(); } },
                { "search_filters", n => { SearchFilters = n.GetObjectValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_search_filters>(global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_search_filters.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_update", AutoUpdate);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_enrichment_payload>("enrichment_payload", EnrichmentPayload);
            writer.WriteBoolValue("exists", Exists);
            writer.WriteBoolValue("has_no_leads", HasNoLeads);
            writer.WriteBoolValue("in_progress", InProgress);
            writer.WriteBoolValue("is_evergreen", IsEvergreen);
            writer.WriteGuidValue("resource_id", ResourceId);
            writer.WriteObjectValue<global::Soenneker.Instantly.OpenApiClient.Api.V2.SupersearchEnrichment.Item.WithResource_GetResponse_search_filters>("search_filters", SearchFilters);
        }
    }
}
#pragma warning restore CS0618
