// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.DfyEmailAccountOrders.Domains.PreWarmedUpList
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PreWarmedUpListPostRequestBody_extensions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "com")]
        #pragma warning disable CS1591
        Com,
        #pragma warning restore CS1591
        [EnumMember(Value = "org")]
        #pragma warning disable CS1591
        Org,
        #pragma warning restore CS1591
        [EnumMember(Value = "co")]
        #pragma warning disable CS1591
        Co,
        #pragma warning restore CS1591
    }
}
