// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Instantly.OpenApiClient.Api.V2.DfyEmailAccountOrders.Domains.PreWarmedUpList
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PreWarmedUpList401Error_error
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Unauthorized")]
        #pragma warning disable CS1591
        Unauthorized,
        #pragma warning restore CS1591
    }
}
